apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: development
type: Opaque
data:
# The values for secrets are base64 encoded and can be generated something like as below - 
# echo -n 'whatever-you-want-encoded'|base64
# 
  mongo-root-username: bW9uZ29hZG1pbg==
  mongo-root-password: bW9uZ29wYXNzd29yZA==
